### ISSUE TITLE
Plugin "netlify-plugin-rss" invalid input "dirToScan"

### ISSUE THREAD

**Issue by guyjames** [sw-yx/netlify-plugin-rss#11]
I have a Hugo site hosted on Netlify and would like to use this plugin for the RSS feed.

I enabled this plugin in the Netlify backend and then copied the config in netlify.toml from the default config suggested, and it gave the error above. I changed it to:

`dirToScan = "/"`

But still it gives the same error message.

The posts are in the default Hugo location of '/content/posts'. I have also tried '/content/posts' in the config file but no luck. I am probably missing something really obvious but I am not able to see what it is.

**Comment by guyjames** [comment]
I think it might be an issue with the netlify plugin itself because it always gives that error on deploy, even if I remove all the relevant code from the netlify.toml file.

**Comment by ehmicky** [comment]
Hi @guyjames,

Could you please share a link to your deploy logs?
Also, if possible, your `netlify.toml`. Thanks!

**Comment by guyjames** [comment]
Not sure if you can read this [deploy log](https://app.netlify.com/sites/guyja-44205/deploys/5ecea19480221c7285d8336b)?

netlify.toml is:

`[build]
publish = "public"
command = "./stackbit-build.sh"

[build.environment]
HUGO_VERSION = "0.63.2"

[[plugins]]
package = "netlify-plugin-rss"
  [plugins.inputs]
  # required configs, customize as needed
  dirToScan = "/posts" # a subfolder to scan. "/" to scan all
  authorName = "swyx"
  site_url = "https://swyx.io"
  title = "Guy James RSS Feed"
  rssDescription = "RSS Feed description"
  categories = ['music']`

I notice they have now removed the RSS plugin from the available Netlify plugins...

**Comment by ehmicky** [comment]
It looks like you've installed this plugin both in the UI and in `netlify.toml`. 
What happens if you uninstall this plugin from your Site's plugins (but keep it in your `netlify.toml`)?

**Comment by guyjames** [comment]
I didn't realise it was either/or, it's not explained in either place. Trying it with just the plugin in the netlify.toml, it gives this error:

`Error: ENOENT: no such file or directory, scandir 'public/posts'`

There is no such directory as 'public' of course, which is why it is failing now, but not sure how to tell it where the correct directory is.

**Comment by ehmicky** [comment]
> I didn't realise it was either/or, it's not explained in either place.

Yes, it's actually a bug on our part that we are currently fixing.

The `dirToScan` input must point to an existing directory. Its directory contains the files to create a RSS feed for.

**Comment by guyjames** [comment]
yes I understand that it must point to an existing directory, 'posts' is an existing directory, although I was not sure if it should be /content/posts which is the usual Hugo structure and which I am using, although that threw the same error when I tried it. So what would be the correct thing to put in that line? Or should I wait until the bug is fixed? Thanks.

**Comment by ehmicky** [comment]
The error `Error: ENOENT: no such file or directory, scandir 'public/posts'` is a separate problem from the one initially posted. For the one initially posted, uninstalling from the UI should work around the problem at the moment.

For the second error, I am not the maintainer of this plugin and am not aware of the specific logic there. @sw-yx Do you know what might be wrong?

**Comment by guyjames** [comment]
Ok but the original error does seem to be related to which directory it's trying to scan, so I would say that the new one is at least related to the original one.

Uninstalling from the UI does seem to have at least changed the error message, yes.

**Comment by ehmicky** [comment]
Those errors are not related, except for the fact they are both about the same `inputs`. But the core problem/bug is different.

**Comment by guyjames** [comment]
Any update on fixing this bug? I would like to be able to use the RSS plugin if possible, thanks. 
@sw-yx

**Comment by guyjames** [comment]
I think I may have found the solution. I added a _redirects file and then changed the line:

`dirToScan = "/posts"`
to
`dirToScan = "/"`

I had tried this before I added the _redirects file and it didn't work, but now it no longer gives an error during deploy. The only downside is that the pages are now included in the RSS feed and not only the posts.

**Comment by ehmicky** [comment]
Great! Do you think this issue should be closed?

**Comment by guyjames** [comment]
It depends if we think that the fact that it only works when scanning the entire site is a separate issue or not. I would like it to only scan the content/posts directory, but it always gives an error when that is specified.

**Comment by guyjames** [comment]
Ok I'm going to close this issue and maybe open another one later for the scanning directory issue.
